<?php
/**
 * @file
 * Install, update, and uninstall functions for the Entity Reference Count
 * module.
 */

/**
 * Implements hook_field_schema().
 */
function entityreference_count_field_schema($field) {
  return array(
    'columns' => array(
      'count' => array(
        'type' => 'int',
        'unsigned' => TRUE,
        'not null' => TRUE,
      ),
    ),
  );
}

/**
 * Implements hook_update_last_removed().
 */
function entityreference_count_update_last_removed() {
  return 7100;
}
